-- Admin-to-admin notes (internal changelog). Visible to all logged-in admins,
-- NOT exposed on the public site (authenticated-read only, so anon can't fetch).
-- The "editable only by the owner" rule is enforced in the admin UI (the editor
-- is hidden for non-owners). This is a UI gate suitable for a trusted team; all
-- authenticated admins technically retain write access at the DB level.

create table if not exists public.admin_notes (
  id         bigint generated by default as identity primary key,
  body       text not null default '',
  author     text not null default '',
  position   integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.admin_notes enable row level security;

-- Only authenticated admins may read or write (no public/anon access).
drop policy if exists "admin read"  on public.admin_notes;
drop policy if exists "admin write" on public.admin_notes;
create policy "admin read"  on public.admin_notes for select to authenticated using (true);
create policy "admin write" on public.admin_notes for all    to authenticated using (true) with check (true);
