-- Public announcements blog (the "Announcements" tab). Each row is a post with
-- a title, markdown body, optional image URLs (one per line), and a date.
-- Public read; authenticated (admin) write — same policy shape as the other
-- editorial tables.

create table if not exists public.announcement_posts (
  id           bigint generated by default as identity primary key,
  title        text not null default '',
  body         text not null default '',
  images       text not null default '',
  post_date    text not null default '',
  author       text not null default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

alter table public.announcement_posts enable row level security;
drop policy if exists "public read"  on public.announcement_posts;
drop policy if exists "admin write" on public.announcement_posts;
create policy "public read"  on public.announcement_posts for select using (true);
create policy "admin write" on public.announcement_posts for all to authenticated using (true) with check (true);
