-- =============================================================
-- Decentraland Map — Daily Scene Changes
-- Paste into Supabase: SQL Editor → New query → Run.
-- Safe to re-run (idempotent). Also folded into supabase/schema.sql.
--
-- Written by: sync-map-changes (Edge Function, service-role key, bypasses RLS).
-- Read by:    map.html / assets/map.js (anon key, via the RPCs below).
-- =============================================================

-- ---------- Tables ----------

-- Single-row checkpoint for the incremental Catalyst sync.
create table if not exists public.map_sync_state (
  id                  integer primary key default 1 check (id = 1),
  last_successful_sync timestamptz,
  last_entity_id       text,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
insert into public.map_sync_state (id) values (1) on conflict (id) do nothing;

-- One row per Catalyst scene deployment (a scene can span multiple parcels —
-- do not confuse this with scene_deployment_parcels below).
create table if not exists public.scene_deployments (
  id                  bigint generated by default as identity primary key,
  entity_id           text not null unique,
  previous_entity_id  text,
  deployed_at         timestamptz,        -- Catalyst entityTimestamp
  detected_at         timestamptz not null default now(),  -- when our sync saw it
  base_parcel_x       integer,
  base_parcel_y       integer,
  scene_name          text,
  metadata            jsonb,
  pointer_data        jsonb,              -- raw pointers array from Catalyst
  parcel_count        integer not null default 0,
  created_at          timestamptz not null default now()
);
create index if not exists scene_deployments_deployed_at_idx on public.scene_deployments (deployed_at desc);
create index if not exists scene_deployments_base_parcel_idx on public.scene_deployments (base_parcel_x, base_parcel_y);

-- Every parcel touched by a deployment (many rows per scene_deployments row).
create table if not exists public.scene_deployment_parcels (
  id             bigint generated by default as identity primary key,
  deployment_id  bigint not null references public.scene_deployments (id) on delete cascade,
  x              integer not null,
  y              integer not null,
  unique (deployment_id, x, y)
);
create index if not exists scene_deployment_parcels_xy_idx on public.scene_deployment_parcels (x, y);
create index if not exists scene_deployment_parcels_deployment_idx on public.scene_deployment_parcels (deployment_id);

-- Daily rollup, one row per UTC date that had at least one deployment.
create table if not exists public.map_daily_stats (
  date              date primary key,
  deployment_count  integer not null default 0,
  scene_count       integer not null default 0,   -- distinct base parcels touched
  parcel_count      integer not null default 0,    -- distinct parcels touched
  updated_at        timestamptz not null default now()
);
create index if not exists map_daily_stats_date_idx on public.map_daily_stats (date desc);

-- ---------- Row Level Security ----------
-- Public (anon) may READ. Nothing writes through PostgREST with the anon key —
-- only the sync-map-changes Edge Function writes, using the service-role key,
-- which bypasses RLS entirely. So there is deliberately no write policy here.

alter table public.map_sync_state          enable row level security;
alter table public.scene_deployments       enable row level security;
alter table public.scene_deployment_parcels enable row level security;
alter table public.map_daily_stats         enable row level security;

do $$
declare t text;
begin
  foreach t in array array['map_sync_state','scene_deployments','scene_deployment_parcels','map_daily_stats'] loop
    execute format('drop policy if exists "public read" on public.%I', t);
    execute format('create policy "public read" on public.%I for select using (true)', t);
  end loop;
end $$;

-- ---------- Read RPCs (called from the browser with the anon key) ----------

-- Deployments in a time window, newest first, each with its full parcel list.
-- Used for both the map's changed-parcel overlay and the "Latest changes" sidebar.
create or replace function public.get_map_changes(
  p_from    timestamptz,
  p_to      timestamptz default now(),
  p_limit   integer default 200,
  p_offset  integer default 0
)
returns jsonb
language sql
stable
as $$
  select coalesce(jsonb_agg(row_to_json(d) order by d.deployed_at desc), '[]'::jsonb)
  from (
    select
      sd.id,
      sd.entity_id,
      sd.previous_entity_id,
      sd.deployed_at,
      sd.base_parcel_x,
      sd.base_parcel_y,
      sd.scene_name,
      sd.parcel_count,
      coalesce(
        (select jsonb_agg(jsonb_build_object('x', p.x, 'y', p.y))
           from public.scene_deployment_parcels p where p.deployment_id = sd.id),
        '[]'::jsonb
      ) as parcels
    from public.scene_deployments sd
    where sd.deployed_at >= p_from and sd.deployed_at <= p_to
    order by sd.deployed_at desc
    limit p_limit offset p_offset
  ) d;
$$;
grant execute on function public.get_map_changes(timestamptz, timestamptz, integer, integer) to anon, authenticated;

-- Full deployment history for a single parcel, newest first.
create or replace function public.get_parcel_history(p_x integer, p_y integer)
returns jsonb
language sql
stable
as $$
  select coalesce(jsonb_agg(row_to_json(d) order by d.deployed_at desc), '[]'::jsonb)
  from (
    select
      sd.id,
      sd.entity_id,
      sd.previous_entity_id,
      sd.deployed_at,
      sd.scene_name,
      sd.parcel_count,
      coalesce(
        (select jsonb_agg(jsonb_build_object('x', p2.x, 'y', p2.y))
           from public.scene_deployment_parcels p2 where p2.deployment_id = sd.id),
        '[]'::jsonb
      ) as parcels
    from public.scene_deployments sd
    where sd.id in (
      select p.deployment_id from public.scene_deployment_parcels p
      where p.x = p_x and p.y = p_y
    )
    order by sd.deployed_at desc
  ) d;
$$;
grant execute on function public.get_parcel_history(integer, integer) to anon, authenticated;

-- Daily stats for the summary cards / "browse changes by day" UI.
create or replace function public.get_map_daily_stats(p_from date, p_to date default current_date)
returns jsonb
language sql
stable
as $$
  select coalesce(jsonb_agg(row_to_json(s) order by s.date desc), '[]'::jsonb)
  from (
    select date, deployment_count, scene_count, parcel_count
    from public.map_daily_stats
    where date >= p_from and date <= p_to
    order by date desc
  ) s;
$$;
grant execute on function public.get_map_daily_stats(date, date) to anon, authenticated;

-- ---------- Internal write helper (called by sync-map-changes, service role only) ----------

-- Recomputes map_daily_stats for exactly the UTC dates given, from the current
-- contents of scene_deployments/scene_deployment_parcels. Safe to call
-- repeatedly for the same date (e.g. several sync runs on the same day, or a
-- backfill that overlaps an already-synced date) since it always derives the
-- absolute count for that day rather than incrementing.
create or replace function public.recompute_map_daily_stats(p_dates date[])
returns void
language sql
as $$
  insert into public.map_daily_stats (date, deployment_count, scene_count, parcel_count, updated_at)
  select
    d.date,
    count(*) as deployment_count,
    count(distinct (sd.base_parcel_x, sd.base_parcel_y)) as scene_count,
    (
      select count(distinct (p.x, p.y))
      from public.scene_deployment_parcels p
      where p.deployment_id in (
        select id from public.scene_deployments
        where date(deployed_at at time zone 'utc') = d.date
      )
    ) as parcel_count,
    now()
  from unnest(p_dates) as d(date)
  join public.scene_deployments sd on date(sd.deployed_at at time zone 'utc') = d.date
  group by d.date
  on conflict (date) do update set
    deployment_count = excluded.deployment_count,
    scene_count = excluded.scene_count,
    parcel_count = excluded.parcel_count,
    updated_at = excluded.updated_at;
$$;
grant execute on function public.recompute_map_daily_stats(date[]) to service_role, authenticated;
